In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import zipfile
zip_ref = zipfile.ZipFile('/content/gdrive/My Drive/Datasets/BaiThi2.zip')
zip_ref.extractall()

In [3]:
import os
import numpy as np


In [32]:
data_spam = os.listdir("/content/TrainData/spam/")
data_not_spam = os.listdir("/content/TrainData/notspam/")


In [33]:
dt_spam = []
label_spam = []
for i in data_spam:
  path = os.path.join("/content/TrainData/spam/", i)
  with open(path, 'r') as f:
    dt_spam.append(f.readlines())
    label_spam.append(int(0))
len(dt_spam)

18

In [34]:
dt_not_spam = []
label_not_spam = []
for i in data_not_spam:
  path = os.path.join("/content/TrainData/notspam/", i)
  with open(path, 'r') as f:
    dt_not_spam.append(f.readlines())
    label_not_spam.append(int(1))
len(dt_not_spam)

193

In [35]:
import random
data_train = dt_spam[:12]+dt_not_spam[:150]
random.seed(0)
random.shuffle(data_train)

label_train = label_spam[:12]+label_not_spam[:150]
random.seed(0)
random.shuffle(label_train)


data_test = dt_spam[12:]+dt_not_spam[150:]
label_test = label_spam[12:]+label_not_spam[150:]
print(len(data_train))
print(len(data_test))

162
49


text processing

In [36]:
import string
import re
import sklearn
from sklearn.feature_extraction._stop_words import ENGLISH_STOP_WORDS

In [47]:
from nltk.stem.porter import PorterStemmer

In [48]:
#cleaning the raw data
def remove_hyperlink(word):
    return  re.sub(r"http\S+", "", word)

def to_lower(word):
    result = word.lower()
    return result

def remove_number(word):
    result = re.sub(r'\d+', '', word)
    return result

def remove_punctuation(word):
    result = word.translate(str.maketrans(dict.fromkeys(string.punctuation)))
    return result

def remove_whitespace(word):
    result = word.strip()
    s = result.split()
    return (' '.join (str (x) for x in s))

def skimming(word):
  stemmer = PorterStemmer()
  singles = [stemmer.stem(x) for x in word.split()]
  return(' '.join(singles))

def replace_newline(word):
    return word.replace('\n','')


def clean_up_pipeline(sentence):
    cleaning_utils = [remove_hyperlink,
                      replace_newline,
                      to_lower,
                      remove_number,
                      remove_punctuation,remove_whitespace,
                      skimming]
    for o in cleaning_utils:
        sentence = o(sentence)
    return sentence

In [10]:
remove_number("  con  sa909324   432424 anh yeu")

'  con  sa    anh yeu'

In [ ]:
remove

In [58]:
X_train = [clean_up_pipeline(str(x)) for x in data_train]
X_test = [clean_up_pipeline(str(x)) for x in data_test]

X_train[0]

'subject re languag acquisit analog pragmaticsn n ye inde care star sentenc sentenc star doe mean passerbi one even brentwood sever week ago wit cruel doubl murder testimoni broken english requir servic profession linguist interpret latter wa nt sure onc o j simpson star sentenc result is futur histori jule levin n'

2. Tokenize

In [59]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

tokenizer.fit_on_texts(X_train)

x_train_features = np.array(tokenizer.texts_to_sequences(X_train))
x_test_features = np.array(tokenizer.texts_to_sequences(X_test))

len(x_train_features[0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


52

In [60]:
for i in range(5):
    print("Text               : ",X_train[i] )
    print("Numerical Sequence : ", x_train_features[i])

Text               :  subject re languag acquisit analog pragmaticsn n ye inde care star sentenc sentenc star doe mean passerbi one even brentwood sever week ago wit cruel doubl murder testimoni broken english requir servic profession linguist interpret latter wa nt sure onc o j simpson star sentenc result is futur histori jule levin n
Numerical Sequence :  [9, 74, 5, 220, 1185, 2275, 2, 319, 1015, 1016, 1412, 589, 589, 1412, 47, 54, 3414, 11, 79, 3415, 250, 107, 343, 1413, 3416, 788, 3417, 3418, 3419, 12, 234, 377, 536, 4, 344, 1017, 10, 34, 272, 452, 171, 172, 3420, 1412, 589, 273, 1, 789, 537, 2276, 3421, 2]
Text               :  subject human sens disambigu correctionn n oh dear first send summari late discov summari ha error second refer ve read g miller commun annual review psycholog vol page sorri mail mark sanderson depart comput scienc univers glasgow g qq scotland uk e mail sanderso dc glasgow ac uk tel x number fax m gonna tent tent tent tent tent both experi ment ment ment 

In [ ]:
tokenizer.index_word

In [61]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(label_train)
y_test = le.transform(label_test)
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1])

In [62]:
embed_size = 20 # how big is each word vector
max_feature = len(tokenizer.word_index)+1
max_len = max_length_sequence = max([len(i) for i in x_train_features])
print("max_feature", max_feature)
print("max_len", max_len)

max_feature 7016
max_len 2277


In [63]:
from keras_preprocessing.sequence import pad_sequences
x_train_features = pad_sequences(x_train_features,maxlen=max_len)
x_test_features = pad_sequences(x_test_features,maxlen=max_len)
x_train_features[0]

array([   0,    0,    0, ..., 2276, 3421,    2], dtype=int32)

4.Model

In [64]:
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation
from keras.layers import Bidirectional
from keras.models import Model
import tensorflow as tf

In [65]:
def create_model():
    
      lstm_model = tf.keras.Sequential()
      lstm_model.add(Embedding(max_feature, 32, input_length=max_len))
      lstm_model.add(LSTM(64))
      lstm_model.add(Dropout(0.5))
      lstm_model.add(Dense(20, activation="relu"))
      lstm_model.add(Dropout(0.4))
      lstm_model.add(Dense(1, activation = "sigmoid"))
      return lstm_model

lstm_model = create_model()
lstm_model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
lstm_model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 2277, 32)          224512    
                                                                 
 lstm_3 (LSTM)               (None, 64)                24832     
                                                                 
 dropout_6 (Dropout)         (None, 64)                0         
                                                                 
 dense_6 (Dense)             (None, 20)                1300      
                                                                 
 dropout_7 (Dropout)         (None, 20)                0         
                                                                 
 dense_7 (Dense)             (None, 1)                 21        
                                                                 
Total params: 250,665
Trainable params: 250,665
Non-tr

In [66]:
his = lstm_model.fit(x_train_features, y_train, batch_size=16, epochs=14, validation_data=(x_test_features, y_test))

Epoch 1/14
11/11 [==============================] - 3s 132ms/step - loss: 0.6592 - accuracy: 0.9012 - val_loss: 0.6075 - val_accuracy: 0.8776
Epoch 2/14
11/11 [==============================] - 1s 81ms/step - loss: 0.4253 - accuracy: 0.9259 - val_loss: 0.5240 - val_accuracy: 0.8776
Epoch 3/14
11/11 [==============================] - 1s 82ms/step - loss: 0.3450 - accuracy: 0.9259 - val_loss: 0.4579 - val_accuracy: 0.8776
Epoch 4/14
11/11 [==============================] - 1s 82ms/step - loss: 0.2687 - accuracy: 0.9259 - val_loss: 0.4001 - val_accuracy: 0.8776
Epoch 5/14
11/11 [==============================] - 1s 82ms/step - loss: 0.2944 - accuracy: 0.9259 - val_loss: 0.3763 - val_accuracy: 0.8776
Epoch 6/14
11/11 [==============================] - 1s 82ms/step - loss: 0.2882 - accuracy: 0.9259 - val_loss: 0.3614 - val_accuracy: 0.8776
Epoch 7/14
11/11 [==============================] - 1s 83ms/step - loss: 0.2900 - accuracy: 0.9259 - val_loss: 0.3571 - val_accuracy: 0.8776
Epoch 8/14
1

In [67]:
lstm_model.save('model_0.9796.h5')

In [68]:
y_predict  = [1 if x>=0.5 else 0 for x in lstm_model.predict(x_test_features)]

from sklearn.metrics import classification_report

print(classification_report(y_test,y_predict))

2/2 [==============================] - 0s 53ms/step
              precision    recall  f1-score   support

           0       1.00      0.83      0.91         6
           1       0.98      1.00      0.99        43

    accuracy                           0.98        49
   macro avg       0.99      0.92      0.95        49
weighted avg       0.98      0.98      0.98        49



label on test

In [ ]:
data_not_spam = os.listdir("/content/TestData_nolabel/")

test_nolabel = []
arr_nolabel=[]
for i in data_not_spam:
  path = os.path.join("/content/TestData_nolabel/", i)
  arr_nolabel.append(i)
  with open(path, 'r') as f:
    test_nolabel.append(f.readlines())

len(test_nolabel)
arr_nolabel

In [71]:
arr_test = [clean_up_pipeline(str(x)) for x in test_nolabel]

arr_test[3]

'subject black hole pre chomskyan citationsn n steve anderson s book morpholog contain follow ing epigraph did nt chang befor public linguist becom scienc linguist begin stand one anoth s shoulder instead one anoth s toe ha point reach point where are redo aspect languag poorli were done first problem origin fact littl had been done syntax prior work gener school littl is comparison ha been done sinc instig movement jakobson s hall s work distinct featur clearli superced pre viou work make difficult structuralist work relev is go today howev anderson is right chide us carri attitud over morpholog where current trend around massachusett ha hardli move beyond bloomfield first claim affix are regular lexic item first rate morpholog cal studi goe back stoic philosoph were first teas apart grammat categori differ track back panini is most current morpholog fail cite relev sourc is fail advantag discoveri struc turalist neogrammarian even classic morphologist pre decessor were particularli a

In [ ]:


from keras.preprocessing.text import Tokenizer
# tokenizer = Tokenizer(num_words=max_feature)

# tokenizer.fit_on_texts(arr_test)

arr_test_feature = np.array(tokenizer.texts_to_sequences(arr_test))

arr_test_feature[0]


In [73]:
from keras_preprocessing.sequence import pad_sequences
arr_test_feature = pad_sequences(arr_test_feature,maxlen=max_len)

arr_test_feature[0]

array([   0,    0,    0, ...,  406, 2443, 2444], dtype=int32)

In [74]:
y_predict_label  = [1 if x>=0.5 else 0 for x in lstm_model.predict(arr_test_feature)]

3/3 [==============================] - 0s 58ms/step


In [75]:
y_predict_label.count(0)

14

In [76]:
with open('/content/label_predict.txt', 'w+') as f:
     
    # write elements of list
    for items in y_predict_label:
        f.write('%s\n' %items)
     
    print("File written successfully")
 
 
# close the file
f.close()

File written successfully


In [79]:
arr_label=list()
with open('/content/label_predict.txt', 'r') as f:
  arr_label.append(f.readlines())
arr_label = np.reshape(arr_label,(78))
arr_la = []
for i in arr_label:
  arr_la.append(int(i[0:1]))
arr_la = ["notspam" if x==1 else "spam" for x in arr_la]
len(arr_la)

78

In [80]:
for i in range(78):
  with open('/content/predict_0.9796.txt', 'w+') as f:
     
    # write elements of list
    for i in range(78):
        f.write('%s' % arr_nolabel[i])
        f.write(",")
        f.write('%s' % arr_la[i])
        f.write('\n')

     
print("File written successfully")

File written successfully
