In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
import zipfile
zip_ref = zipfile.ZipFile('/content/gdrive/My Drive/Datasets/BaiThi2.zip')
zip_ref.extractall()

In [4]:
import os
import numpy as np


In [93]:
data_spam = os.listdir("/content/TrainData/spam/")
data_not_spam = os.listdir("/content/TrainData/notspam/")


In [94]:
dt_spam = []
label_spam = []
for i in data_spam:
  path = os.path.join("/content/TrainData/spam/", i)
  with open(path, 'r') as f:
    dt_spam.append(f.readlines())
    label_spam.append(int(0))
len(dt_spam)

18

In [95]:
dt_not_spam = []
label_not_spam = []
for i in data_not_spam:
  path = os.path.join("/content/TrainData/notspam/", i)
  with open(path, 'r') as f:
    dt_not_spam.append(f.readlines())
    label_not_spam.append(int(1))
len(dt_not_spam)

193

In [96]:
import random
data_train = dt_spam[:12]+dt_not_spam[:150]
random.seed(0)
random.shuffle(data_train)

label_train = label_spam[:12]+label_not_spam[:150]
random.seed(0)
random.shuffle(label_train)


data_test = dt_spam[12:]+dt_not_spam[150:]
label_test = label_spam[12:]+label_not_spam[150:]
print(len(data_train))
print(len(data_test))

162
49


text processing

In [78]:
import string
import re
import sklearn
from sklearn.feature_extraction._stop_words import ENGLISH_STOP_WORDS

In [79]:
#cleaning the raw data
def remove_hyperlink(word):
    return  re.sub(r"http\S+", "", word)

def to_lower(word):
    result = word.lower()
    return result

def remove_number(word):
    result = re.sub(r'\d+', '', word)
    return result

def remove_punctuation(word):
    result = word.translate(str.maketrans(dict.fromkeys(string.punctuation)))
    return result

def remove_whitespace(word):
    result = word.strip()
    s = result.split()
    return (' '.join (str (x) for x in s))
    

def replace_newline(word):
    return word.replace('\n','')


def clean_up_pipeline(sentence):
    cleaning_utils = [remove_hyperlink,
                      replace_newline,
                      to_lower,
                      remove_number,
                      remove_punctuation,remove_whitespace]
    for o in cleaning_utils:
        sentence = o(sentence)
    return sentence

In [97]:
X_train = [clean_up_pipeline(str(x)) for x in data_train]
X_test = [clean_up_pipeline(str(x)) for x in data_test]

X_train[0]

'subject re language acquisition analogy pragmaticsn n yes indeed careful star sentence sentencing star does meaning passerby one evening brentwood several weeks ago witnessed cruel double murder testimony broken english required services professional linguist interpret latter was nt sure once o j simpson starred sentence result is future history jules levin n'

2. Tokenize

In [98]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

tokenizer.fit_on_texts(X_train)

x_train_features = np.array(tokenizer.texts_to_sequences(X_train))
x_test_features = np.array(tokenizer.texts_to_sequences(X_test))

len(x_train_features[0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


52

In [99]:
for i in range(5):
    print("Text               : ",X_train[i] )
    print("Numerical Sequence : ", x_train_features[i])

Text               :  subject re language acquisition analogy pragmaticsn n yes indeed careful star sentence sentencing star does meaning passerby one evening brentwood several weeks ago witnessed cruel double murder testimony broken english required services professional linguist interpret latter was nt sure once o j simpson starred sentence result is future history jules levin n
Numerical Sequence :  [7, 53, 6, 164, 1447, 2590, 2, 319, 962, 2591, 2592, 621, 4072, 2592, 33, 172, 4073, 11, 1160, 4074, 320, 401, 259, 4075, 4076, 708, 4077, 4078, 4079, 12, 2593, 709, 495, 70, 4080, 963, 10, 27, 213, 357, 173, 120, 4081, 4082, 621, 1161, 1, 710, 496, 2594, 4083, 2]
Text               :  subject human sense disambiguation correctionn n oh dear first send summary late discover summary has error second reference ve read g miller communication annual review psychology vol pages sorry mail mark sanderson department computing science university glasgow g qq scotland uk e mail sanderso dcs glasg

In [ ]:
tokenizer.index_word

In [101]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(label_train)
y_test = le.transform(label_test)
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1])

In [102]:
embed_size = 20 # how big is each word vector
max_feature = len(tokenizer.word_index)+1
max_len = max_length_sequence = max([len(i) for i in x_train_features])
print("max_feature", max_feature)
print("max_len", max_len)

max_feature 8895
max_len 2277


In [103]:
from keras_preprocessing.sequence import pad_sequences
x_train_features = pad_sequences(x_train_features,maxlen=max_len)
x_test_features = pad_sequences(x_test_features,maxlen=max_len)
x_train_features[0]

array([   0,    0,    0, ..., 2594, 4083,    2], dtype=int32)

4.Model

In [104]:
from keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation
from keras.layers import Bidirectional
from keras.models import Model
import tensorflow as tf

In [105]:
def create_model():
    
      lstm_model = tf.keras.Sequential()
      lstm_model.add(Embedding(max_feature, 32, input_length=max_len))
      lstm_model.add(LSTM(64))
      lstm_model.add(Dropout(0.5))
      lstm_model.add(Dense(20, activation="relu"))
      lstm_model.add(Dropout(0.4))
      lstm_model.add(Dense(1, activation = "sigmoid"))
      return lstm_model

lstm_model = create_model()
lstm_model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
lstm_model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 2277, 32)          284640    
                                                                 
 lstm_7 (LSTM)               (None, 64)                24832     
                                                                 
 dropout_12 (Dropout)        (None, 64)                0         
                                                                 
 dense_14 (Dense)            (None, 20)                1300      
                                                                 
 dropout_13 (Dropout)        (None, 20)                0         
                                                                 
 dense_15 (Dense)            (None, 1)                 21        
                                                                 
Total params: 310,793
Trainable params: 310,793
Non-tr

In [106]:
his = lstm_model.fit(x_train_features, y_train, batch_size=16, epochs=14, validation_data=(x_test_features, y_test))

Epoch 1/14
11/11 [==============================] - 3s 133ms/step - loss: 0.6657 - accuracy: 0.8395 - val_loss: 0.6102 - val_accuracy: 0.8776
Epoch 2/14
11/11 [==============================] - 1s 82ms/step - loss: 0.4710 - accuracy: 0.9198 - val_loss: 0.4429 - val_accuracy: 0.8776
Epoch 3/14
11/11 [==============================] - 1s 82ms/step - loss: 0.3204 - accuracy: 0.9198 - val_loss: 0.3860 - val_accuracy: 0.8776
Epoch 4/14
11/11 [==============================] - 1s 82ms/step - loss: 0.3032 - accuracy: 0.9259 - val_loss: 0.3569 - val_accuracy: 0.8776
Epoch 5/14
11/11 [==============================] - 1s 82ms/step - loss: 0.3041 - accuracy: 0.9259 - val_loss: 0.3419 - val_accuracy: 0.8776
Epoch 6/14
11/11 [==============================] - 1s 85ms/step - loss: 0.2652 - accuracy: 0.9259 - val_loss: 0.3750 - val_accuracy: 0.8776
Epoch 7/14
11/11 [==============================] - 1s 84ms/step - loss: 0.2170 - accuracy: 0.9259 - val_loss: 0.2627 - val_accuracy: 0.8776
Epoch 8/14
1

In [116]:
y_predict  = [1 if x>=0.5 else 0 for x in lstm_model.predict(x_test_features)]

from sklearn.metrics import classification_report

print(classification_report(y_test,y_predict))

2/2 [==============================] - 0s 60ms/step
              precision    recall  f1-score   support

           0       1.00      0.83      0.91         6
           1       0.98      1.00      0.99        43

    accuracy                           0.98        49
   macro avg       0.99      0.92      0.95        49
weighted avg       0.98      0.98      0.98        49



label on test

In [117]:
data_not_spam = os.listdir("/content/TestData_nolabel/")

test_nolabel = []

for i in data_not_spam:
  path = os.path.join("/content/TestData_nolabel/", i)
  with open(path, 'r') as f:
    test_nolabel.append(f.readlines())
len(test_nolabel)


78

In [118]:
arr_test = [clean_up_pipeline(str(x)) for x in test_nolabel]

arr_test[3]

'subject black hole pre chomskyan citationsn n steve anderson s book morphology contain follow ing epigraph did nt change before publication linguistics become science linguists begin standing one another s shoulders instead one another s toes has point reached point where are redoing aspects language poorly were done first problem originated fact little had been done syntax prior work generative school little is comparison has been done since instigation movement jakobson s halle s work distinctive features clearly superceded pre vious work making difficult structuralist work relevant is going today however anderson is right chiding us carrying attitude over morphology where current trend around massachusetts has hardly moved beyond bloomfield first claim affixes are regular lexical items first rate morphologi cal study goes back stoic philosophers were first tease apart grammatical categories different track back panini is most current morphology failing cite relevant sources is fail

In [119]:


from keras.preprocessing.text import Tokenizer
# tokenizer = Tokenizer(num_words=max_feature)

# tokenizer.fit_on_texts(arr_test)

arr_test_feature = np.array(tokenizer.texts_to_sequences(arr_test))

arr_test_feature[0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


[7,
 53,
 469,
 4393,
 5261,
 2,
 221,
 899,
 555,
 459,
 4,
 29,
 230,
 469,
 340,
 3,
 78,
 1212,
 265,
 1,
 313,
 2636,
 1049,
 262,
 1613,
 3072,
 463,
 79,
 1090,
 1044,
 140,
 205,
 259,
 506,
 9,
 463,
 601,
 2252,
 213,
 1,
 1339,
 1478,
 3722,
 2444,
 7091,
 78,
 899,
 4175,
 359,
 5710,
 17,
 5524,
 2636,
 865,
 1,
 464,
 250,
 1192,
 835,
 105,
 469,
 246,
 555,
 2823,
 36,
 77,
 2212,
 2358,
 205,
 124,
 11,
 427,
 10,
 70,
 847,
 469,
 124,
 6074,
 178,
 667,
 469,
 10,
 11,
 250,
 496,
 60,
 976,
 821,
 96,
 847,
 29,
 14,
 1243,
 200,
 142,
 3,
 579,
 17,
 265,
 1,
 3268,
 579,
 498,
 2941,
 748,
 352,
 2828,
 2829]

In [120]:
from keras_preprocessing.sequence import pad_sequences
arr_test_feature = pad_sequences(arr_test_feature,maxlen=max_len)

arr_test_feature[0]

array([   0,    0,    0, ...,  352, 2828, 2829], dtype=int32)

In [121]:
y_predict_label  = [1 if x>=0.5 else 0 for x in lstm_model.predict(arr_test_feature)]

3/3 [==============================] - 0s 58ms/step


In [122]:
y_predict_label.count(0)

17

In [124]:
with open('/content/label_predict.txt', 'w+') as f:
     
    # write elements of list
    for items in y_predict_label:
        f.write('%s\n' %items)
     
    print("File written successfully")
 
 
# close the file
f.close()

File written successfully
